AY2122S2-CS2113-T11-1/tp

src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Ui.java
text-ui-test/EXPECTED.TXT

Add Ui class and the function to read in user input.

---

src/main/java/seedu/duke/AddItemCommand.java
src/main/java/seedu/duke/Command.java
src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/EmptyItemNameException.java
src/main/java/seedu/duke/EmptyItemPaxException.java
src/main/java/seedu/duke/ExitCommand.java
src/main/java/seedu/duke/HotelLiteManagerException.java
src/main/java/seedu/duke/InvalidCommandException.java
src/main/java/seedu/duke/InvalidItemPaxException.java
src/main/java/seedu/duke/Ui.java
src/main/java/seedu/duke/WrongCommandException.java
src/test/java/seedu/duke/DukeTest.java

Update code to implement command parsing for add item command.

---

src/main/java/seedu/duke/AddItemCommand.java
src/main/java/seedu/duke/Command.java
src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/EmptyItemNameException.java
src/main/java/seedu/duke/EmptyItemPaxException.java
src/main/java/seedu/duke/ExitCommand.java
src/main/java/seedu/duke/InvalidItemPaxException.java
src/main/java/seedu/duke/Item.java
src/main/java/seedu/duke/ItemList.java
src/main/java/seedu/duke/Ui.java
src/test/java/seedu/duke/DukeTest.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Update code to implement add item to item list functionality.

---

src/main/java/seedu/duke/AddSatisfactionCommand.java
src/main/java/seedu/duke/EmptySatisfactionCustomerException.java
src/main/java/seedu/duke/EmptySatisfactionValueException.java
src/main/java/seedu/duke/InvalidSatisfactionValueException.java
src/main/java/seedu/duke/Satisfaction.java
src/main/java/seedu/duke/SatisfactionList.java
src/main/java/seedu/duke/ViewSatisfactionsCommand.java

Fixes #48, fixes #46, fixes #42

Finish JavaDoc, final fix to exceptions

---

src/main/java/seedu/duke/AddAvailabilityCommand.java
src/main/java/seedu/duke/AddHousekeeperCommand.java
src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/Housekeeper.java
src/main/java/seedu/duke/HousekeeperList.java
src/main/java/seedu/duke/InvalidAgeException.java
src/main/java/seedu/duke/InvalidAvailabilityException.java
src/main/java/seedu/duke/InvalidHousekeeperProfile.java
src/main/java/seedu/duke/WrongCommandException.java
src/test/java/seedu/duke/DukeTest.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Add function to add availability of housekeeper

---

src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/Ui.java
src/main/java/seedu/duke/ViewHousekeeperListCommand.java
src/test/java/seedu/duke/DukeTest.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Implement function to view Housekeeper List

---

src/main/java/seedu/duke/AddAvailabilityCommand.java
src/main/java/seedu/duke/AddHousekeeperCommand.java
src/main/java/seedu/duke/HousekeeperList.java
src/main/java/seedu/duke/InvalidAgeException.java
src/main/java/seedu/duke/InvalidUserException.java
src/main/java/seedu/duke/UserExistException.java
src/test/java/seedu/duke/AddAvailabilityTest.java
src/test/java/seedu/duke/AddHousekeeperTest.java
src/test/java/seedu/duke/DukeTest.java
text-ui-test/EXPECTED.TXT

Create exceptions class for invalid user issues

---

src/main/java/seedu/duke/AddAvailabilityCommand.java
src/main/java/seedu/duke/AddHousekeeperCommand.java
src/test/java/seedu/duke/AddHousekeeperTest.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Add logging into add profile and availability of housekeeper

---

src/main/java/seedu/duke/AverageSatisfactionCommand.java
src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/SatisfactionList.java

Impelement average satisfaction, refactor view satisfactions

---

src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/DeleteItemCommand.java
src/main/java/seedu/duke/Item.java
src/main/java/seedu/duke/ItemList.java
src/main/java/seedu/duke/ItemNotFoundException.java
src/main/java/seedu/duke/Ui.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Update code to implement delete item functionality.

---

src/main/java/seedu/duke/AddItemCommand.java
src/main/java/seedu/duke/CommandParser.java
src/test/java/seedu/duke/DukeTest.java
src/test/java/seedu/duke/UpdateItemCommandTest.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Update code to change the Add Item Command Format.

---

src/main/java/seedu/duke/AddHousekeeperCommand.java
src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/HousekeeperList.java
src/main/java/seedu/duke/OverAgeException.java
src/main/java/seedu/duke/UnderAgeException.java
src/test/java/seedu/duke/AddHousekeeperTest.java
text-ui-test/EXPECTED.TXT

Implement age restriction for Housekeeper

---

src/main/java/seedu/duke/UpdateItemPaxCommand.java
src/test/java/seedu/duke/UpdateItemCommandTest.java
text-ui-test/input.txt

Update code to change the UpdateItemPaxCommand formatting.

---

src/main/java/seedu/duke/AddAvailabilityCommand.java
src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/EmptyDayException.java
src/main/java/seedu/duke/GetAvailableHousekeeper.java
src/main/java/seedu/duke/Housekeeper.java
src/main/java/seedu/duke/HousekeeperList.java
src/main/java/seedu/duke/InvalidAvailabilityException.java
src/main/java/seedu/duke/InvalidDayException.java
src/main/java/seedu/duke/Ui.java
src/test/java/seedu/duke/AddAvailabilityTest.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Implement function to view housekeeper available on either any day from Monday to Sunday

---

src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/Housekeeper.java
src/main/java/seedu/duke/HousekeeperList.java
src/main/java/seedu/duke/ResetAvailabilityCommand.java
src/main/java/seedu/duke/Ui.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Add reset availability function

---

src/main/java/seedu/duke/AddAvailabilityCommand.java
src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/DeleteHousekeeperCommand.java
src/main/java/seedu/duke/EmptyNameException.java
src/main/java/seedu/duke/HousekeeperList.java
src/main/java/seedu/duke/UserDoesNotExistException.java
src/test/java/seedu/duke/AddHousekeeperTest.java

Add delete housekeeper from list feature

---

src/main/java/seedu/duke/AgeIncreaseCommand.java
src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/HousekeeperList.java
src/main/java/seedu/duke/InvalidHousekeeperProfile.java
src/main/java/seedu/duke/Ui.java
text-ui-test/EXPECTED.TXT

Faliciaong update age by one

---

src/main/java/seedu/duke/Housekeeper.java

Fix duplicated days in availability

---

src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/ItemList.java
src/main/java/seedu/duke/Ui.java
src/main/java/seedu/duke/UpdateItemNameCommand.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Update code to implement the update item name functionaility.

---

src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/EmptyKeywordException.java
src/main/java/seedu/duke/ItemList.java
src/main/java/seedu/duke/SearchItemCommand.java
src/main/java/seedu/duke/Ui.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Update Code to Implement the Search Items functionality.

---

docs/UserGuide.md

Falicia user guide

---

src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/ItemList.java
src/main/java/seedu/duke/UpdateItemPaxCommand.java
src/main/java/seedu/duke/ViewItemWithZeroPaxCommand.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Implement the functionality to view all items with pax 0 in the list.

---

src/main/java/seedu/duke/Ui.java
text-ui-test/EXPECTED.TXT

Update code to implement list header and tail.

---

src/main/java/seedu/duke/AddAvailabilityCommand.java
src/main/java/seedu/duke/AddHousekeeperCommand.java
src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/DeleteHousekeeperCommand.java
src/main/java/seedu/duke/GetAvailableHousekeeperCommand.java
src/main/java/seedu/duke/HousekeeperList.java

Refractor to meet SLAP for housekeeper commands

---

src/main/java/seedu/duke/ItemList.java
src/main/java/seedu/duke/Ui.java
src/main/java/seedu/duke/command/itemcommand/AddItemCommand.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Update code to check for duplicate items in the item list before adding

---

src/main/java/seedu/duke/Event.java
src/main/java/seedu/duke/EventList.java
src/main/java/seedu/duke/ListContainer.java
src/main/java/seedu/duke/command/eventcommands/ViewEventCommand.java
src/main/java/seedu/duke/storage/EventListFileManager.java

Basic structure of events

---

src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/Ui.java
src/main/java/seedu/duke/command/itemcommand/AddItemCommand.java
src/main/java/seedu/duke/command/itemcommand/UpdateItemNameCommand.java
src/test/java/seedu/duke/AddAvailabilityTest.java
src/test/java/seedu/duke/AddHousekeeperTest.java
src/test/java/seedu/duke/AssignHousekeeperTest.java
src/test/java/seedu/duke/DukeTest.java
src/test/java/seedu/duke/UpdateItemCommandTest.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Update code to make user input case insensitive

---

src/main/java/seedu/duke/InvalidAvailabilityException.java
src/main/java/seedu/duke/InvalidHousekeeperProfile.java
text-ui-test/EXPECTED.TXT

Update exceptions for housekeeper

---

src/main/java/seedu/duke/command/housekeepercommands/GetAvailableHousekeeperCommand.java

Faliciaong fix trim input

---

src/main/java/seedu/duke/InvalidUpdateItemNameCommandException.java
src/main/java/seedu/duke/InvalidUpdateItemPaxCommandException.java
src/main/java/seedu/duke/command/itemcommand/AddItemCommand.java
src/main/java/seedu/duke/command/itemcommand/UpdateItemNameCommand.java
src/main/java/seedu/duke/command/itemcommand/UpdateItemPaxCommand.java
src/test/java/seedu/duke/UpdateItemCommandTest.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Update code to implement the exceptions for update item command

---

src/main/java/seedu/duke/NameNotStringException.java
src/main/java/seedu/duke/command/housekeepercommands/AddHousekeeperCommand.java
src/test/java/seedu/duke/AddHousekeeperTest.java

Update to ensure name does not contain symbol and digit

---

src/main/java/seedu/duke/command/itemcommand/AddItemCommand.java
src/main/java/seedu/duke/command/itemcommand/UpdateItemPaxCommand.java
src/test/java/seedu/duke/UpdateItemCommandTest.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Update code to implement a limit on the item's pax

---

src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/InvalidNewWeekException.java
src/main/java/seedu/duke/InvalidNewYearException.java
src/main/java/seedu/duke/InvalidViewHousekeeperException.java
src/main/java/seedu/duke/Ui.java
src/main/java/seedu/duke/command/housekeepercommands/AgeIncreaseCommand.java
src/main/java/seedu/duke/command/housekeepercommands/ResetAvailabilityCommand.java
src/main/java/seedu/duke/command/housekeepercommands/ViewHousekeeperListCommand.java
text-ui-test/EXPECTED.TXT

Faliciaong fix view and new week year

---

src/main/java/seedu/duke/InvalidHousekeeperProfileException.java
src/main/java/seedu/duke/command/assigncommand/AssignHousekeeperCommand.java
src/main/java/seedu/duke/command/eventcommands/AddEventCommand.java
src/main/java/seedu/duke/command/eventcommands/DeleteEventCommand.java
src/main/java/seedu/duke/command/eventcommands/ViewEventsCommand.java
src/main/java/seedu/duke/command/housekeepercommands/AddAvailabilityCommand.java
src/main/java/seedu/duke/command/housekeepercommands/AddHousekeeperCommand.java
src/test/java/seedu/duke/AddAvailabilityTest.java
src/test/java/seedu/duke/AddHousekeeperTest.java

Faliciaong fix slashes

---

docs/UserGuide.md

Update the user guide to include the item commands

---

src/main/java/seedu/duke/AssignmentMap.java
src/main/java/seedu/duke/Housekeeper.java
src/main/java/seedu/duke/Ui.java
src/main/java/seedu/duke/command/housekeepercommands/AddAvailabilityCommand.java
src/main/java/seedu/duke/command/housekeepercommands/DeleteHousekeeperCommand.java
text-ui-test/EXPECTED.TXT

Faliciaong change printing

---

src/main/java/seedu/duke/AddHousekeeperPerformanceCommand.java
src/main/java/seedu/duke/EmptyItemPaxException.java
src/main/java/seedu/duke/InvalidItemPaxException.java
src/main/java/seedu/duke/InvalidUpdateItemNameCommandException.java
src/main/java/seedu/duke/InvalidUpdateItemPaxCommandException.java
src/main/java/seedu/duke/InvalidViewItemsCommandException.java
src/main/java/seedu/duke/InvalidViewItemsWithZeroPaxCommandException.java
src/main/java/seedu/duke/ItemFileNotFoundException.java
src/main/java/seedu/duke/ItemList.java
src/main/java/seedu/duke/command/itemcommands/AddItemCommand.java
src/main/java/seedu/duke/command/itemcommands/DeleteItemCommand.java
src/main/java/seedu/duke/command/itemcommands/SearchItemCommand.java
src/main/java/seedu/duke/command/itemcommands/UpdateItemNameCommand.java
src/main/java/seedu/duke/command/itemcommands/UpdateItemPaxCommand.java
src/main/java/seedu/duke/command/itemcommands/ViewItemListCommand.java
src/main/java/seedu/duke/command/itemcommands/ViewItemsWithZeroPaxCommand.java
src/main/java/seedu/duke/exceptions/EmptyItemNameException.java

Update the javadocs for all the items related functions and classes

---

src/main/java/seedu/duke/DuplicateItemNameException.java
src/main/java/seedu/duke/command/itemcommands/UpdateItemNameCommand.java

Update code to fix duplicate item name bug

---

src/main/java/seedu/duke/command/housekeepercommands/GetAvailableHousekeeperCommand.java

Fix assertion error

---

src/main/java/seedu/duke/command/itemcommands/UpdateItemPaxCommand.java
src/test/java/seedu/duke/UpdateItemCommandTest.java
text-ui-test/EXPECTED.TXT

Update code to throw the correct exception

---

src/main/java/seedu/duke/Duke.java

Update to disable logging

---

src/main/java/seedu/duke/command/itemcommands/UpdateItemNameCommand.java
src/main/java/seedu/duke/exceptions/ItemNameAlreadyInListException.java
src/main/java/seedu/duke/exceptions/ItemNotFoundException.java
src/main/java/seedu/duke/itemlists/ItemList.java

Update code to fix the duplicate item name error for update item command

---

src/main/java/seedu/duke/command/itemcommands/AddItemCommand.java
src/main/java/seedu/duke/exceptions/InvalidItemNameException.java
src/main/java/seedu/duke/exceptions/ItemAlreadyInListException.java
src/main/java/seedu/duke/itemlists/Item.java
src/main/java/seedu/duke/itemlists/ItemList.java
text-ui-test/EXPECTED.TXT

Update code to fix the error which allows invalid symbols in item name

---

src/main/java/seedu/duke/command/housekeepercommands/AddAvailabilityCommand.java
src/main/java/seedu/duke/housekeeperlists/Housekeeper.java

Fix crashing on extra spacing for availability command

---

ListFolder/ItemList.txt
ListFolder/housekeeper_file.txt
src/main/java/seedu/duke/command/itemcommands/UpdateItemPaxCommand.java
src/main/java/seedu/duke/exceptions/NewItemPaxSameAsCurrentPaxException.java
src/main/java/seedu/duke/itemlists/ItemList.java

Update code to fix the error of the updating the item pax to be the same

---

docs/UserGuide.md
src/main/java/seedu/duke/command/itemcommands/UpdateItemNameCommand.java
src/main/java/seedu/duke/itemlists/Item.java

Update code to implement the item name constraint and add it in the UG

---

docs/UserGuide.md
src/main/java/seedu/duke/command/eventcommands/AddEventCommand.java
src/main/java/seedu/duke/command/eventcommands/DeleteEventCommand.java
src/main/java/seedu/duke/eventlists/EventList.java
src/main/java/seedu/duke/exceptions/EventDoesNotExist.java
src/main/java/seedu/duke/exceptions/InvalidDeleteEventException.java

This PR closes #289, #318, #305, #303, #302 and #279

Fixes some PE-D bugs

---

docs/team/siewyangzhi.md

Add SiewYangZhi's PPP

---

src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Ui.java

Update code to refactor the write to file method

---

src/main/java/seedu/duke/CommandParser.java
src/main/java/seedu/duke/Ui.java
src/main/java/seedu/duke/command/HelpCommand.java
src/main/java/seedu/duke/command/eventcommands/ViewEventsCommand.java

Help Command added to display everything

---

docs/DeveloperGuide.md

Setting up Manual testing format

---

src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Ui.java
src/main/java/seedu/duke/command/housekeepercommands/AddAvailabilityCommand.java
src/main/java/seedu/duke/command/housekeepercommands/AddHousekeeperCommand.java
src/main/java/seedu/duke/command/housekeepercommands/AgeIncreaseCommand.java
src/main/java/seedu/duke/command/housekeepercommands/DeleteHousekeeperCommand.java
src/main/java/seedu/duke/command/housekeepercommands/GetAvailableHousekeeperCommand.java
src/main/java/seedu/duke/command/housekeepercommands/ResetAvailabilityCommand.java
src/main/java/seedu/duke/command/housekeepercommands/ViewHousekeeperListCommand.java
src/main/java/seedu/duke/housekeeperlists/HousekeeperList.java
src/main/java/seedu/duke/storage/HousekeeperFileManager.java

Faliciaong javadocs final

---

docs/DeveloperGuide.md

Add the decription of the architecture diagram into the DG
